from dataclasses import dataclass
from enum import IntEnum

from schemas.astrology import SourceType


class SourcePriority(IntEnum):
    """Priority used when evaluating evidence for astrology claims."""

    PRIMARY_CLASSICAL = 1
    AUTHORITATIVE_BOOK = 2
    SCHOLAR = 3
    JOURNAL = 4
    REPUTABLE_MODERN = 5
    MODEL_INFERENCE = 6


@dataclass(frozen=True)
class SourceDefinition:
    """Definition of a research source or source family."""

    source_id: str
    title: str
    source_type: SourceType
    priority: SourcePriority
    description: str
    verification_required: bool = True


SOURCE_REGISTRY: tuple[SourceDefinition, ...] = (
    SourceDefinition(
        source_id="BPHS",
        title="Brihat Parashara Hora Shastra",
        source_type=SourceType.CLASSICAL_TEXT,
        priority=SourcePriority.PRIMARY_CLASSICAL,
        description=(
            "Primary classical Jyotish source for Parashari principles, "
            "planetary significations, houses, signs, yogas, dashas, "
            "divisional charts, and related predictive principles."
        ),
    ),
    SourceDefinition(
        source_id="PHALADEEPIKA",
        title="Phaladeepika",
        source_type=SourceType.CLASSICAL_TEXT,
        priority=SourcePriority.PRIMARY_CLASSICAL,
        description=(
            "Classical Jyotish text used for planetary, house, sign, "
            "yoga, and predictive principles."
        ),
    ),
    SourceDefinition(
        source_id="SARAVALI",
        title="Saravali",
        source_type=SourceType.CLASSICAL_TEXT,
        priority=SourcePriority.PRIMARY_CLASSICAL,
        description=(
            "Classical Jyotish text used as supporting evidence for "
            "traditional interpretive and predictive principles."
        ),
    ),
    SourceDefinition(
        source_id="JYOTISH_PARASHAR_CODE",
        title=(
            "Jyotish: Parashar Code Of Prediction, Bhava & Yoga Analysis, "
            "Based on Ten Prime Classics"
        ),
        source_type=SourceType.BOOK,
        priority=SourcePriority.AUTHORITATIVE_BOOK,
        description=(
            "Preferred modern reference for the Celestial Jyotish research "
            "workflow when the relevant principle is covered by the book."
        ),
    ),
    SourceDefinition(
        source_id="SCHOLAR",
        title="Recognized Jyotish scholar or specialist work",
        source_type=SourceType.SCHOLAR,
        priority=SourcePriority.SCHOLAR,
        description=(
            "Scholarly interpretation or analysis attributed to an "
            "identifiable Jyotish scholar."
        ),
    ),
    SourceDefinition(
        source_id="JOURNAL",
        title="Peer-reviewed or reputable research journal",
        source_type=SourceType.JOURNAL,
        priority=SourcePriority.JOURNAL,
        description=(
            "Academic or specialist research relevant to the claim. "
            "Use only when the publication and evidence can be identified."
        ),
    ),
    SourceDefinition(
        source_id="REPUTABLE_MODERN",
        title="Reputable modern reference",
        source_type=SourceType.REPUTABLE_MODERN_SOURCE,
        priority=SourcePriority.REPUTABLE_MODERN,
        description=(
            "A reputable contemporary source used for terminology, "
            "context, documentation, or clearly attributed interpretation."
        ),
    ),
    SourceDefinition(
        source_id="MODEL_INFERENCE",
        title="Model inference",
        source_type=SourceType.MODEL_INFERENCE,
        priority=SourcePriority.MODEL_INFERENCE,
        description=(
            "Reasoning generated by an AI model without independently "
            "verified source evidence. It must never be treated as a "
            "classical or externally verified claim."
        ),
        verification_required=True,
    ),
)


def get_source(source_id: str) -> SourceDefinition | None:
    """Return a source definition by its registry identifier."""

    normalized_id = source_id.strip().upper()

    for source in SOURCE_REGISTRY:
        if source.source_id == normalized_id:
            return source

    return None


def get_sources_by_type(
    source_type: SourceType,
) -> tuple[SourceDefinition, ...]:
    """Return all registered sources belonging to a source type."""

    return tuple(
        source
        for source in SOURCE_REGISTRY
        if source.source_type == source_type
    )


def get_research_hierarchy() -> tuple[SourceDefinition, ...]:
    """Return registered sources in research-priority order."""

    return tuple(
        sorted(
            SOURCE_REGISTRY,
            key=lambda source: source.priority,
        )
    )


def is_model_inference(source_type: SourceType) -> bool:
    """Return True when a source type represents model-generated inference."""

    return source_type == SourceType.MODEL_INFERENCE